repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
      - id: flake8
        args: [--max-line-length=100]

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [--line-length=79]
