sudo: false
language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - env: TOXENV=openapi

services:
  - mongodb

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  email: false
