language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=openapi
    - python: 3.7
      env: TOXENV=docs

services:
  - docker
  - mongodb

before_install:
  - pip install tox
  - tox -e docker-build -- smoke
  - docker run -d --net=host xsnippet/xsnippet-api:smoke

install:
  - pip install tox coveralls

script:
  - tox
  # TODO: replace the sanity check below with proper functional testing
  - curl http://127.0.0.1:8000/snippets

after_success:
  - coveralls

notifications:
  email: false
