sudo: false
language: python
python: 3.5

services:
  - mongodb

install:
  # see 'concurrency=greenlet' option in .coveragerc for reason behind greenlet
  - pip install tox coveralls greenlet

script:
  - tox

after_success:
  - coveralls

notifications:
  email: false
