dist: trusty
sudo: required
language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - env: TOXENV=openapi

services:
  - docker
  - mongodb

before_install:
  - docker build -t xsnippet_api -f contrib/docker/Dockerfile .
  - docker run -d --net=host xsnippet_api

install:
  - pip install tox coveralls

script:
  - tox
  # TODO: replace the sanity check below with proper functional testing
  - curl http://127.0.0.1:8000/snippets

after_success:
  - coveralls

notifications:
  email: false
