sudo: false
language: python
python: 3.5

services:
  - mongodb

install:
  # greenlet is needed to submit concurrency=greenlet based coverage
  # to coveralls.io service
  - pip install tox coveralls greenlet

script:
  - tox

after_success:
  - coveralls

notifications:
  email: false
