application: xsnppt
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: favicon.ico

- url: /.*
  script: dispatcher.py
