application: xsnppt
version: 1
runtime: python27
api_version: 1
threadsafe: true


libraries:
- name: PIL
  version: "1.1.7"

- name: jinja2
  version: "2.6"

handlers:
- url: /static
  static_dir: data/static

- url: /favicon.ico
  static_files: data/static/images/favicon.ico
  upload: data/static/images/favicon.ico

- url: /robots.txt
  static_files: data/static/robots.txt
  upload: data/static/robots.txt

- url: /google7734a10e4d4c894f.html
  static_files: static/verifications/google7734a10e4d4c894f.html
  upload: data/static/verifications/google7734a10e4d4c894f.html

- url: /yandex_78be63ee9b494616.html
  static_files: static/verifications/yandex_78be63ee9b494616.html
  upload: data/static/verifications/yandex_78be63ee9b494616.html

- url: /.*
  script: xsnippet.application

builtins:
- datastore_admin: on
