application: xsnppt
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /google7734a10e4d4c894f.html
  static_files: static/verifications/google7734a10e4d4c894f.html
  upload: static/verifications/google7734a10e4d4c894f.html

- url: /yandex_6fbaa0368039cfec.html
  static_files: static/verifications/yandex_6fbaa0368039cfec.html
  upload: static/verifications/yandex_6fbaa0368039cfec.html

- url: /.*
  script: dispatcher.py

builtins:
- datastore_admin: on
