[package]
name = "xsnippet-api"
version = "5.0.0"
authors = ["XSnippet Team <dev@xsnippet.org>"]
edition = "2018"
description = "XSnippet is a simple web-service for sharing code snippets on the Internet."
readme = "README.md"
homepage = "https://xsnippet.org/"
repository = "https://github.com/xsnippet/xsnippet-api/"
license = "MIT"
keywords = ["snippets", "snippet", "code", "storage", "api"]
categories = [
    "web-programming",
    "web-programming::http-server",
]
publish = false

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.5", features = ["chrono", "postgres", "r2d2"] }
jsonwebtoken = "7.2.0"
rand = "0.7.3"
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
rocket = "0.4.5"
rocket_contrib = {version = "0.4.5", features = ["json"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
uuid = { version = "0.8.2", features = ["v4"] }

[dev-dependencies]
tempfile = "3.2.0"
