# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/storage/sql/schema.rs"

[migrations_directory]
dir = "src/storage/sql/migrations"
